### ISSUE TITLE
Selecting and displaying a team

### ISSUE THREAD

**Issue by WakkaTrout** [minorleaguegrayonassociates/GrayonSlam#10]
### Description:
As a baseball fan, I want to be able to display all of the information stored about a desired team so that I can see how my stay at their stadium will feel

### Assumptions:
* Team/stadium data can be loaded in to the program and accessed
* The main window has been initialized

### Estimate:
* 3

### Tasks:
1. Create a view for displaying the team name, League they are in, and Stadium information
2. Give the user the ability to navigate and select a specific team/stadium from the data for display
3. Populate the view with the information of the specified team
4. Should be able to be cleared and updated with different information when a user selects a different team

### Tests:
1. Verify that the correct team/stadium data and corresponding stadium data is loaded in
2. Verify that incorrect/stadium data is not loaded in along with the correct team
3. Verify that when a different team is selected, the old team does not persist in the display

### Definition of Done:
A baseball fan can navigate the UI and select a team for display and all of the team information and stadium information displays correctly for the fans viewing pleasure within the UI.

**Comment by ChrisRzech** [comment]
Should be closed by #59, closing
