### ISSUE TITLE
Display teams' league along with stadium

### ISSUE THREAD

**Issue by yosmo78** [minorleaguegrayonassociates/GrayonSlam#13]
### Description:
As an avid baseball fan of many different baseball leagues, I want to view and sort teams' leagues along with their stadium information so that I can group together different teams with the same leagues.

### Assumptions:
* That there exist a data format for reading values of the team
  - These values are stadium information and league information
* There exists a data structure for holding the values of the team
* That data from an input source has populated the internal way for storing data

### Estimate:
* 5

### Tasks:
1. Be able to read out the team data from the internal data-structure
2. Query the user for what type of league data they want to view
3. Add only the teams that meet the league requirements to a list
4. Sort the list by team name or stadium name (user choice)
5. Add graphical implementation for the list displaying team names and stadium

### Tests:
1. Verify that the correct teams are added to the list
2. Verify that the list is viewable
3. Verify that the league chosen is what will be the case for populating the list
4. Verify that Major, American, and National support are all present
5. Make sure that list is lexicographically sorted by team name or stadium name

### Definition of Done:
The user can view a list of stadiums and their teams that is sortable by leagues.

**Comment by ChrisRzech** [comment]
~~Should be closed by #53, closing~~
wrong story

**Comment by ChrisRzech** [comment]
Should be closed by #59, closing
