### ISSUE TITLE
Display stadium(s) and team name(s) that has only smallest/greatest distance to center field

### ISSUE THREAD

**Issue by yosmo78** [minorleaguegrayonassociates/GrayonSlam#15]
### Description:
As a stadium architectural student, I would like to know only the stadium(s) and team name(s) that has smallest/greatest distance to center field so that I can quickly find examples of the extremes in stadium construction (Requirements 12 & 13 second page)

### Assumptions:
* There exists a way of viewing stadiums and team names (display)
* There exists a way of receiving input to the user

### Estimate:
* 3

### Tasks:
1. Query user if they want the greatest distance to center field or shortest distance
2. Find the stadium (or stadiums if multiple have equal greatest/shortest distances) with either the greatest/shortest distance in the list
3. Display only that stadium

### Tests:
1. Verify user input is received correctly
2. Verify that the stadium found has actually the greatest/shortest distances to center field
3. Verify that the output of the stadium and team is correct
4. Verify that if no stadiums are present then output that there are no stadiums present

### Definition of Done:
This story is considered done when the user can request for the stadium with the greatest/shortest distances to center field and the information is displayed to the user in the form of the stadium(s) and the team name(s)

**Comment by ChrisRzech** [comment]
Should be closed by #59, closing
