### ISSUE TITLE
Sort and display Stadiums

### ISSUE THREAD

**Issue by WakkaTrout** [minorleaguegrayonassociates/GrayonSlam#16]
### Description:
As a baseball fanatic, I want to be able to see all of the stadiums along with the name of the teams that play there sorted by the typology of the stadium, chronology of the opening date of the stadium, and seating capacity of the stadiums so that I can plan my trip just the way I want to.

### Assumptions:
* The main window has been initialized
* The data for the stadiums has been loaded into the program

### Estimate:
* 13

### Tasks:
* Create a view for displaying the stadiums and their information
* Give the user the ability to navigate to a list of the stadiums sorted in the desired way
* Populate the view with the desired sorted list of stadiums
* If the user ever decides to sort in a different way, it should clear the old list and display a new one

### Tests:
* Verify that the all desired stadiums are loaded in to the view
* Verify that stadiums that are not desired are not loaded in along with the correct stadiums
* Verify that the stadiums are sorted in the desired fashion

### Definition of Done:
The user can access the list of stadiums along with the names of the teams that play at each stadium sorted in the desired fashion.

**Comment by ChrisRzech** [comment]
Should be closed by #53, closing
