### ISSUE TITLE
GUI user story

### ISSUE THREAD

**Issue by yosmo78** [minorleaguegrayonassociates/GrayonSlam#2]
### Description:
As a visual learner I would like all the information pertaining to my vacation and all the baseball teams to be displayed graphically in a UI so that I can easily digest it and know what I am in for.

### Assumptions:
* The UI will display all necessary information for the user
* The user may not be too tech savvy so the UI should be easy to navigate

### Estimate:
* 5

### Tasks:
1. As the an avid baseball trip planner, I would like to see the weighted graph so that I can better visualize how long the actual trips will be and how close/far apart the stadiums are to each other
1. As a UI guru, I would like to see a nice clean user interface that is intuitive and easily navigable and understandable.
1. As a number person, I would like to see list of all information pertaining to the baseball teams and stadiums

### Test: 
1. Verify that the UI displays properly on systems for which the project is compiled to run on
2. Verify that the graph displays correctly
3. Verify that other tasks display properly within the UI

### Definition of Done:
This is considered done when the application has an easy to navigate interface that allows users to access any of the options without having to dig through too many different layers of links/windows

**Comment by ChrisRzech** [comment]
Similar to #37, closing
