### ISSUE TITLE
Dijkistra's/A* and recursive shortest path algorithms

### ISSUE THREAD

**Issue by WakkaTrout** [minorleaguegrayonassociates/GrayonSlam#24]
### Description:
As an trip application designer, I want to have Dijkstra's/A* shortest path algorithm and a recursive shortest path algorithm for a weighted graph so I can give my users the shortest trip when I design my trips.

### Assumptions:
* The weighted graph is implemented

### Estimate:
* 8

### Tasks
* Implement Dijkstra's/A* algorithm on a given weighted graph given 2 vertices
* Implement a recursive shortest path algorithm on a given weighted graph given 2 vertices (recursively choosing the next shortest path on each vertex--note that this doesn't always give the shortest path)

### Tests:
* Verify that shortest path that an algorithm can calculate in the graph is returned

### Definition of Done:
Dijkstra's/A* return the shortest path between two vertices in a graph given two vertices and the recursive shortest path gives a (not always) short path.

**Comment by ChrisRzech** [comment]
Should be closed by #65, closing
