### ISSUE TITLE
Add database to load any data needed in the program

### ISSUE THREAD

**Issue by Roger-Chavez** [minorleaguegrayonassociates/GrayonSlam#56]
### Description:
As an administrator, I want to be able to load data into and save using a database entity that exists as long as the program runs so that I can use data from files anywhere in the program.

### Assumptions:
none

### Estimate:
* 8

### Tasks:
* Set ids to stadiums and teams
* Add stadiums to `.csv` file
* Make `.csv` file for distances and add id's to distances
* Add map coordinates to MLBInfo
* Make expansion `.csv`
* Make parser to load
* Make save function for data persistence 
* Instantiate data to appropriate types
* Make getters to get containers or  find teams/stadiums by ids

### Tests:
* That all the data loads and saves correctly
* Print container of teams / stadiums to console 
* Print container of distances to the console
* Print coordinates to the console
* Make sure the program is persistent

### Definition of Done:
Able to load all the data from the `.csv` and print container of teams / stadiums to console, able to print container of distances to the console, able to print coordinates to the console and when editing data and loading new data make sure the program is persistent.

**Comment by ChrisRzech** [comment]
Should be closed by #33, closing
